/*
 * This file is generated by jOOQ.
 */
package com.kbalazsworks.smartscrumpokerbackend.db;


import com.kbalazsworks.smartscrumpokerbackend.db.tables.FlywaySchemaHistory;
import com.kbalazsworks.smartscrumpokerbackend.db.tables.Poker;
import com.kbalazsworks.smartscrumpokerbackend.db.tables.Ticket;


/**
 * Convenience access to all tables in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.poker</code>.
     */
    public static final Poker POKER = Poker.POKER;

    /**
     * The table <code>public.ticket</code>.
     */
    public static final Ticket TICKET = Ticket.TICKET;
}
