#I need a github action for java 21 distribution zulu and gradle:
#  name: Java CI with Gradle native build
#  and checkout repo
#  and setup java env
#  and get the version from gradle version property
#  and create a psql gha service with version:16.2 password:passwords username:username db:smartscrumpoker
#  and install dependencies with gradle
#  and build the app with gradle on GHA server
name: Java CI with Gradle native build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16.2
        env:
          POSTGRES_PASSWORD: passwords
          POSTGRES_USER: username
          POSTGRES_DB: smartscrumpoker
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: 'zulu'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Get project version
        id: project_version
        run: |
          echo "PROJECT_VERSION=$(./gradlew properties -q | grep "version:" | awk '{print $2}')" >> $GITHUB_ENV

      - name: Print project version
        run: echo ${{ env.PROJECT_VERSION }}

      - name: Install dependencies
        run: ./gradlew dependencies

      - name: Build with Gradle
        run: ./gradlew build