name: Java CI with Gradle native build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16.2
        env:
          POSTGRES_PASSWORD: admin_pass
          POSTGRES_USER: admin
          POSTGRES_DB: smartscrumpoker
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: 'zulu'

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Get project version
        id: project_version
        run: |
          echo "PROJECT_VERSION=$(./gradlew properties -q | grep "version:" | awk '{print $2}')" >> $GITHUB_ENV
          echo "COMMIT_SHA_SHORT=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"

      - name: Print project version
        run: echo ${{ env.PROJECT_VERSION }}

      - name: Install dependencies
        run: ./gradlew dependencies

      - name: Build with Gradle
        env:
          SERVER_ENV: DEV
          SERVER_PORT: 9999
          SERVER_SOCKER_FULL_HOST: wss://localhost:9999/ws
          SERVER_SSL_ENABLED: true
          SERVER_SSL_KEY_STORE: classpath:keystore/dev.p12
          SERVER_SSL_KEY_STORE_PASSWORD: password
          SITE_DOMAIN: not.yet
          SITE_FRONTEND_HOST: https://localhost:4200
          SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: 10
          SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: 10
          SPRING_DATASOURCE_PASSWORD: admin_pass
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/smartscrumpoker
          SPRING_DATASOURCE_USERNAME: admin
          SOCKET_IS_ENABLED_SOCKET_CONNECT_AND_DISCONNECT_LISTENERS: false
        run: ./gradlew build

      - name: Print output folder target
        run: ls -l  ${{ github.workspace }}/build/libs

      - name: Upload .jar artifact
        uses: actions/upload-artifact@v2
        with:
          name: jar-artifact
          path:  ${{ github.workspace }}/build/libs/SmartScrumPokerBackend-${{ env.PROJECT_VERSION }}.jar
          retention-days: 7

      - name: Copy created .jar for docker
        run: |
          cp ${{ github.workspace }}/build/libs/SmartScrumPokerBackend-${{ env.PROJECT_VERSION }}.jar ./SmartScrumPokerBackend-latest.jar

      - name: Print workspace & root
        run: |
          ls -l  ${{ github.workspace }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: kbalazsworks/smart_scrum_poker_backend:${{ env.PROJECT_VERSION }}, kbalazsworks/smart_scrum_poker_backend:latest, kbalazsworks/smart_scrum_poker_backend:commit_sha_short_${{ env.COMMIT_SHA_SHORT }}
