#generate a github action master flow for this repo with dockerhub push and get the version from gradle version property with:
#  java version 21 distribution zulu
#  and use setup-buildx-action@v3
# and don't add username to tag
name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: 'zulu'

      - name: Get project version
        id: project_version
        run: |
          echo "PROJECT_VERSION=$(./gradlew properties -q | grep "version:" | awk '{print $2}')" >> $GITHUB_ENV

      - name: Print project version
        run: echo ${{ env.PROJECT_VERSION }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: kbalazsworks/smart_scrum_poker_backend:${{ env.PROJECT_VERSION }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}