#I need a github action for java 21 and gradle:
#  and checkout repo
#  and setup java env
#  and get the version from gradle version property
#  and install dependencies with gradle
#  and build the app with gradle on GHA server
name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Get project version
        id: project_version
        run: |
          echo "PROJECT_VERSION=$(./gradlew properties -q | grep "version:" | awk '{print $2}')" >> $GITHUB_ENV

      - name: Print project version
        run: echo $PROJECT_VERSION

      - name: Install dependencies
        run: ./gradlew dependencies

      - name: Build with Gradle
        run: ./gradlew build
